import json
from pathlib import Path

nb_path = Path("getting_started_gemma_4_hadl_dualloop.ipynb")
nb = json.loads(nb_path.read_text(encoding="utf-8"))

cell_source = [
    "# Clean and create agent directory\n",
    "if AGENT_DIR.exists():\n",
    "    shutil.rmtree(AGENT_DIR, ignore_errors=True)\n",
    "AGENT_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "# Canonical 6-file Championship Bundle (Top 1 Aligned: 0.15 - 0.17+ Target)\n",
    "# Key Innovations:\n",
    "# 1. Generous 6.0-minute budget (allows multi-step fixes for medium tasks, total ~7h << 9h Kaggle limit)\n",
    "# 2. Full issue handoff to code_analyzer first (never misled by external issue stack traces)\n",
    "# 3. Issue rules: exact naming, strip PR boilerplate, support executable docs_src/ (11.6% benchmark)\n",
    "# 4. Full 5-tool code_analyzer including search_similar_code in isolated sub-agent context\n",
    "AGENT_FILES = {\n",
    '  "agent.yaml": """name: swe_coder\n',
    "model: gemma-4-31b-it-qat-w4a16-ct\n",
    "description: Autonomous software engineer that fixes repository issues with minimal, verified patches.\n",
    "instruction: !include prompts/system.md\n",
    "generate_content_config: !include configs/sampling.yaml\n",
    "tools:\n",
    "  - run_command\n",
    "  - read_file\n",
    "  - edit_file\n",
    "  - write_file\n",
    "  - get_status\n",
    "  - submit_patch\n",
    "  - agent_tool:\n",
    "      config_path: sub_agents/code_analyzer.yaml\n",
    "      skip_summarization: true\n",
    '""",\n',
    '  "configs/sampling.yaml": """temperature: 0.2\n',
    "top_p: 0.95\n",
    "top_k: 40\n",
    "max_output_tokens: 8192\n",
    "thinking_config:\n",
    "  thinking_budget: 4096\n",
    "  include_thoughts: false\n",
    '""",\n',
    '  "eval_config.yaml": """evaluation:\n',
    "  timeout_seconds: 90\n",
    "  max_tool_calls: 50\n",
    "  max_time_minutes: 6\n",
    "  max_turns: 80\n",
    '""",\n',
    '  "prompts/analyzer.md": """You are `code_analyzer`, a read-only code navigation specialist. You never modify files.\n',
    "Given an issue, find exactly where it must be fixed.\n",
    "\n",
    "## Tools\n",
    '- `run_command` for READ-ONLY commands only: `grep -rn`, `ls`, `sed -n`, `git log -p -S`\n',
    "- `search_similar_code` for concepts the issue describes without naming code\n",
    "- `get_code_neighbors` to walk callers and callees\n",
    "- `get_code_subgraph` to see how a few candidate symbols connect\n",
    "- `read_file` with tight line ranges to confirm\n",
    "\n",
    "## Method\n",
    "1. Skip pull-request template boilerplate in the issue. Extract identifiers: function/class names, error messages, file paths, options, and any NEW names the issue asks for.\n",
    "2. Search for each one, then follow the call chain until you reach the line where behaviour diverges from what the issue expects.\n",
    "3. Confirm by reading the actual code. Never guess line numbers.\n",
    "\n",
    "## Answer format (at most 250 words, nothing else)\n",
    "LOCATION: <path>:<start>-<end> (<function or class>)\n",
    "ROOT CAUSE: <one or two sentences>\n",
    "FIX PLAN: <concrete change, using the exact names the issue uses>\n",
    'RELATED: <other call sites or files needing the same change, or "none">\n',
    "TESTS: <existing test files that exercise this code>\n",
    "CONFIDENCE: high | medium | low\n",
    '""",\n',
    '  "prompts/system.md": """You are an autonomous senior Python engineer working inside a sandboxed checkout of a real open-source repository at /workspace.\n',
    "Goal: resolve the issue in the user message with the smallest correct patch, then call `submit_patch`.\n",
    "\n",
    "## Hard rules\n",
    "- Never edit, add or delete tests, `conftest.py`, `pytest.ini`, CI or packaging files. Hidden tests are applied after you finish.\n",
    "- Keep public APIs backward compatible unless the issue explicitly asks for a change.\n",
    "- Scratch files go to /tmp only. Anything left in /workspace becomes part of your patch.\n",
    "- The environment is pre-built: do not try to install packages.\n",
    "- Always finish by calling `submit_patch`. A careful best-effort fix beats no patch.\n",
    "\n",
    "## Reading the issue\n",
    "- Many issues are pasted pull-request descriptions. Ignore the template parts (HTML comments, discussion links, checklists, AI disclaimers). The title, code snippets, error messages and API names are the real specification.\n",
    "- The hidden tests usually add new test functions that exercise exactly what the issue describes. If the issue names a new parameter, function, class, option or message, use exactly that name and spelling, and implement it completely, including the edge cases it mentions.\n",
    "- Runnable documentation examples (for example `docs_src/`) are real code that tests import. Change them when the issue is about them.\n",
    "\n",
    "## Workflow\n",
    "1. **Understand**: state the expected vs. actual behaviour to yourself in one or two sentences.\n",
    "2. **Localize**:\n",
    "   - Call the `code_analyzer` tool with the full issue text first. It returns LOCATION / ROOT CAUSE / FIX PLAN. Verify its claim by reading those exact lines before editing.\n",
    '   - Extract every identifier, error message and file name from the issue and search for them: `grep -rn "<identifier>" --include=*.py . | head -30`.\n',
    "   - Read only the lines you need (`read_file` with a line range or `sed -n 'START,ENDp' FILE`).\n",
    "3. **Reproduce**: write a minimal script to /tmp/repro.py that shows the bug and run it with `python /tmp/repro.py`.\n",
    "4. **Fix**: edit source files with `edit_file`. Copy `old_string` verbatim from the file, *including leading indentation*, and strip any line-number prefixes. Keep `old_string` short but unique. One logical change per edit. Fix the root cause, not the symptom, and also handle the edge cases the issue mentions.\n",
    "5. **Verify**: run `python -m py_compile <file>` after every edit, rerun /tmp/repro.py, then run the closest existing tests: `python -m pytest <tests/path> -x -q` (narrow with `-k`).\n",
    "6. **Submit**: run `git status` and `git diff`, make sure only intended source changes remain, then call `submit_patch`.\n",
    "\n",
    "## Budget discipline\n",
    "- Call `get_status` every ~8 tool calls. When less than 25% of turns or time remain, stop exploring and go straight to Fix → Verify → Submit.\n",
    "- Keep outputs short: pipe through `head`, use `grep -n`, `pytest -q`. Never print whole large files.\n",
    "- If an edit fails twice, re-read the exact lines and retry with a smaller unique snippet.\n",
    "\n",
    "## Quality bar\n",
    "- Match the surrounding code style, type hints and naming.\n",
    "- Prefer a small, targeted change over a refactor. Touch other files only when the fix requires it.\n",
    '""",\n',
    '  "sub_agents/code_analyzer.yaml": """name: code_analyzer\n',
    "model: gemma-4-31b-it-qat-w4a16-ct\n",
    "description: Read-only code navigator. Given an issue, returns the exact location, root cause and a fix plan.\n",
    "instruction: !include ../prompts/analyzer.md\n",
    "generate_content_config: !include ../configs/sampling.yaml\n",
    "tools:\n",
    "  - run_command\n",
    "  - read_file\n",
    "  - search_similar_code\n",
    "  - get_code_neighbors\n",
    "  - get_code_subgraph\n",
    '""",\n',
    "}\n",
    "\n",
    "# Write all agent files\n",
    "for rel_path, content in sorted(AGENT_FILES.items()):\n",
    "    target_file = AGENT_DIR / rel_path\n",
    "    target_file.parent.mkdir(parents=True, exist_ok=True)\n",
    "    target_file.write_text(content.strip() + '\\n', encoding='utf-8')\n",
    "\n",
    "print(f'[+] Materialized Agent X-Alpha Dual-Loop hierarchy in: {AGENT_DIR}')\n",
    "print(f'    Total files written: {len(AGENT_FILES)}')\n",
    "for f in sorted(AGENT_FILES.keys()):\n",
    "    print(f'     - {f} ({len(AGENT_FILES[f]):,} chars)')\n",
    "\n",
    "# Safe tasks loading (handles hidden dataset variations without crashing)\n",
    "TASKS_PATH = DATA_DIR / 'tasks.jsonl'\n",
    "tasks = []\n",
    "if TASKS_PATH.exists():\n",
    "    try:\n",
    "        with open(TASKS_PATH, 'r', encoding='utf-8') as f:\n",
    "            for line in f:\n",
    "                if line.strip():\n",
    "                    tasks.append(json.loads(line))\n",
    "        print(f'[+] Loaded {len(tasks)} tasks from {TASKS_PATH.name}')\n",
    "        for t in tasks[:3]:\n",
    '            print(f\'     - {t.get("instance_id", "task")} ({t.get("repo", "repo")})\')\n',
    "    except Exception as e:\n",
    "        print(f'[*] Tasks parsing note: {e}')\n",
    "else:\n",
    "    print('[*] tasks.jsonl not present in data dir; proceeding in standalone packaging mode.')\n",
]

for cell in nb["cells"]:
    if "AGENT_FILES =" in "".join(cell.get("source", [])):
        cell["source"] = cell_source
        break

nb_path.write_text(json.dumps(nb, indent=1), encoding="utf-8")
print("[+] Successfully updated getting_started notebook to Goldilocks 0.17+ Championship Bundle!")
