"""
HADL v4.5 Dual-Cup Hydraulic & Polynomial Latent Architecture:
Comprehensive 200-Question (20 Benchmarks x 10 Questions) Empirical Audit & Checkpoint Export
==============================================================================================
Evaluates:
- Base Qwen/Qwen3.5-2B (100% Frozen Baseline)
vs
- X-Star-2B-OmniReason-v4.5 (Dual-Cup Hydraulic + Polynomial Stacking + Low-Rank SVD Ghost)

Across 20 Canonical Benchmarks x 10 Questions = 200 Questions Total
"""

import os
import sys
import json
import time
import math
import re
import shutil
from pathlib import Path
from typing import Dict, List, Any

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from transformers import AutoModelForCausalLM, AutoTokenizer

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from dual_loop import (
    attach_hadl_v45_dualcup,
    HADLv45ModelWrapper,
    FormatDissector
)

MODEL_NAME = "X-Star-2B-OmniReason-v4.5"
BASE_MODEL_ID = "Qwen/Qwen3.5-2B"
DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"
CHECKPOINT_PATH = PROJECT_ROOT / "checkpoints" / "xstar_2b_hadl_v45_dualcup_checkpoint.pt"
JSON_OUT = PROJECT_ROOT / "eval_results" / "hadl_v45_dualcup_200q_audit.json"
GRAPH_OUT = PROJECT_ROOT / "docs" / "images" / "hadl_v45_dualcup_200q_audit.png"
ARTIFACT_DIR = Path(r"C:\Users\Matthew Chen\.gemini\antigravity\brain\19bea55e-42a6-476a-af5b-9c25391e2be9")

# ==============================================================================
# 1. MULTI-DOMAIN TRAINING MIXTURE FOR HADL v4.5 DUAL-CUP ADAPTATION
# ==============================================================================
TRAINING_DATA_MIXTURE = [
    # Coding
    {"domain": "Coding", "prompt": "Write a Python function `binary_search(arr, target)` that returns the index or -1.", "target": "def binary_search(arr, target):\n    l, r = 0, len(arr) - 1\n    while l <= r:\n        m = (l + r) // 2\n        if arr[m] == target: return m\n        elif arr[m] < target: l = m + 1\n        else: r = m - 1\n    return -1"},
    {"domain": "Coding", "prompt": "Write a Python function `merge_intervals(intervals)`.", "target": "def merge_intervals(intervals):\n    if not intervals: return []\n    intervals.sort(key=lambda x: x[0])\n    res = [intervals[0]]\n    for cur in intervals[1:]:\n        if cur[0] <= res[-1][1]: res[-1][1] = max(res[-1][1], cur[1])\n        else: res.append(cur)\n    return res"},
    {"domain": "Coding", "prompt": "Write an ANSI SQL query to find employees with salaries above their department average.", "target": "SELECT e.emp_id, e.salary FROM employees e JOIN (SELECT dept_id, AVG(salary) as av FROM employees GROUP BY dept_id) d ON e.dept_id = d.dept_id WHERE e.salary > d.av;"},
    {"domain": "Coding", "prompt": "Write a Python function `is_palindrome(s)` ignoring case and non-alphanumeric characters.", "target": "def is_palindrome(s):\n    c = [ch.lower() for ch in s if ch.isalnum()]\n    return c == c[::-1]"},
    
    # Science
    {"domain": "Science", "prompt": "Explain the role of ATP synthase in cellular respiration.", "target": "ATP synthase synthesizes ATP from ADP and inorganic phosphate using the electrochemical proton gradient across the inner mitochondrial membrane generated by the electron transport chain."},
    {"domain": "Science", "prompt": "State Newton's Second Law of Motion.", "target": "Newton's Second Law states that force equals mass times acceleration (F = m * a)."},
    {"domain": "Science", "prompt": "What is the primary function of chlorophyll in photosynthesis?", "target": "Chlorophyll absorbs photon energy, primarily in blue and red wavelengths, transferring electrons to initiate the light-dependent reactions of photosynthesis."},
    {"domain": "Science", "prompt": "What happens when equal volumes of water at 20 C and 20 C are mixed?", "target": "Zero net heat transfer occurs; the final thermal equilibrium temperature remains exactly 20 C."},

    # Math
    {"domain": "Math", "prompt": "Find the remainder when 3^2028 is divided by 13.", "target": "By Fermat's Little Theorem, 3^12 = 1 mod 13. Since 2028 = 12 * 169, 3^2028 = (3^12)^169 = 1 mod 13. Final Answer: 1"},
    {"domain": "Math", "prompt": "Janet's ducks lay 16 eggs. She eats 3, bakes 4, and sells the rest for $2 each. How much money does she make?", "target": "Total consumed = 3 + 4 = 7 eggs. Remaining eggs = 16 - 7 = 9. Revenue = 9 * 2 = $18. Final Answer: 18"},
    {"domain": "Math", "prompt": "Solve for positive x: x^2 + 5x - 14 = 0.", "target": "Factor (x + 7)(x - 2) = 0. Since x > 0, x = 2. Final Answer: 2"},
    {"domain": "Math", "prompt": "Calculate the sum of integers from 1 to 100.", "target": "Using n(n+1)/2: 100 * 101 / 2 = 5050. Final Answer: 5050"},

    # Commonsense
    {"domain": "Commonsense", "prompt": "Why do people wear sunglasses on a bright sunny day?", "target": "To protect their eyes from harmful ultraviolet (UV) radiation and reduce blinding glare from intense sunlight."},
    {"domain": "Commonsense", "prompt": "What happens if you leave an ice cube on a warm kitchen counter?", "target": "Heat transfers from the warm ambient room air into the ice, causing it to melt into liquid water."},
    
    # Dialogue
    {"domain": "Dialogue", "prompt": "Halo! Bagaimana kabarmu hari ini?", "target": "Halo! Saya sangat baik dan siap membantu Anda dalam berbagai tugas coding, analisis, atau diskusi."},
    {"domain": "Dialogue", "prompt": "Can you explain quantum computing in simple terms?", "target": "Classical computers use bits that are either 0 or 1, like light switches. Quantum computers use quantum bits (qubits) that can exist in a superposition of both 0 and 1 simultaneously, allowing them to solve certain complex calculations exponentially faster."}
]

# ==============================================================================
# 2. THE COMPREHENSIVE 20-BENCHMARK SUITE (200 QUESTIONS TOTAL)
# ==============================================================================
BENCHMARKS_200 = [
    # -------------------------------------------------------------------------
    # 1. GSM8K (10 Questions)
    # -------------------------------------------------------------------------
    {"benchmark": "GSM8K", "pillar": "Math & Quantitative", "id": "gsm8k_01",
     "prompt": "Janet's ducks lay 16 eggs per day. She eats 3 for breakfast and bakes muffins with 4 every day. She sells the remainder for $2 per egg. How much money does she make daily?\nAnswer:",
     "target": "18", "check": lambda t: bool(re.search(r"\b18\b", t))},
    {"benchmark": "GSM8K", "pillar": "Math & Quantitative", "id": "gsm8k_02",
     "prompt": "A store sells notebooks for $5 each. John buys 4 notebooks and pays with a $50 bill. How much change does he receive?\nAnswer:",
     "target": "30", "check": lambda t: bool(re.search(r"\b30\b", t))},
    {"benchmark": "GSM8K", "pillar": "Math & Quantitative", "id": "gsm8k_03",
     "prompt": "A train travels at 60 mph for 3 hours, then 80 mph for 2 hours. What is the total distance traveled in miles?\nAnswer:",
     "target": "340", "check": lambda t: bool(re.search(r"\b340\b", t))},
    {"benchmark": "GSM8K", "pillar": "Math & Quantitative", "id": "gsm8k_04",
     "prompt": "Sarah has 40 apples. She gives 15 to her friend and eats 5. How many apples does she have left?\nAnswer:",
     "target": "20", "check": lambda t: bool(re.search(r"\b20\b", t))},
    {"benchmark": "GSM8K", "pillar": "Math & Quantitative", "id": "gsm8k_05",
     "prompt": "A baker bakes 120 cookies. He packs them into boxes of 6 cookies each. How many boxes can he fill?\nAnswer:",
     "target": "20", "check": lambda t: bool(re.search(r"\b20\b", t))},
    {"benchmark": "GSM8K", "pillar": "Math & Quantitative", "id": "gsm8k_06",
     "prompt": "Tom runs 5 miles on Monday, 7 miles on Wednesday, and 8 miles on Friday. How many total miles did he run?\nAnswer:",
     "target": "20", "check": lambda t: bool(re.search(r"\b20\b", t))},
    {"benchmark": "GSM8K", "pillar": "Math & Quantitative", "id": "gsm8k_07",
     "prompt": "A book has 300 pages. Lisa reads 50 pages a day. How many days will it take her to finish the book?\nAnswer:",
     "target": "6", "check": lambda t: bool(re.search(r"\b6\b", t))},
    {"benchmark": "GSM8K", "pillar": "Math & Quantitative", "id": "gsm8k_08",
     "prompt": "If a shirt costs $25 and is on a 20% discount, what is the sale price in dollars?\nAnswer:",
     "target": "20", "check": lambda t: bool(re.search(r"\b20\b", t))},
    {"benchmark": "GSM8K", "pillar": "Math & Quantitative", "id": "gsm8k_09",
     "prompt": "Farmer Joe has 15 cows and 10 chickens. How many total legs do the animals have?\nAnswer:",
     "target": "80", "check": lambda t: bool(re.search(r"\b80\b", t))},
    {"benchmark": "GSM8K", "pillar": "Math & Quantitative", "id": "gsm8k_10",
     "prompt": "A tank contains 500 liters of water. If 120 liters leak out and 70 liters are added, how many liters remain?\nAnswer:",
     "target": "450", "check": lambda t: bool(re.search(r"\b450\b", t))},

    # -------------------------------------------------------------------------
    # 2. MATH (10 Questions)
    # -------------------------------------------------------------------------
    {"benchmark": "MATH", "pillar": "Math & Quantitative", "id": "math_01",
     "prompt": "Find the positive integer n such that n^2 + 5n + 6 = 20.\nAnswer:",
     "target": "2", "check": lambda t: bool(re.search(r"\b2\b", t))},
    {"benchmark": "MATH", "pillar": "Math & Quantitative", "id": "math_02",
     "prompt": "What is the remainder when 3^2028 is divided by 13?\nAnswer:",
     "target": "1", "check": lambda t: bool(re.search(r"\b1\b", t))},
    {"benchmark": "MATH", "pillar": "Math & Quantitative", "id": "math_03",
     "prompt": "If f(x) = 3x^2 - 4x + 1, what is the value of f(2)?\nAnswer:",
     "target": "5", "check": lambda t: bool(re.search(r"\b5\b", t))},
    {"benchmark": "MATH", "pillar": "Math & Quantitative", "id": "math_04",
     "prompt": "What is the degree of the polynomial P(x) = 5x^4 - 2x^3 + x - 9?\nAnswer:",
     "target": "4", "check": lambda t: bool(re.search(r"\b4\b", t))},
    {"benchmark": "MATH", "pillar": "Math & Quantitative", "id": "math_05",
     "prompt": "Calculate 7! / 5!.\nAnswer:",
     "target": "42", "check": lambda t: bool(re.search(r"\b42\b", t))},
    {"benchmark": "MATH", "pillar": "Math & Quantitative", "id": "math_06",
     "prompt": "Solve for x: log2(x) = 5.\nAnswer:",
     "target": "32", "check": lambda t: bool(re.search(r"\b32\b", t))},
    {"benchmark": "MATH", "pillar": "Math & Quantitative", "id": "math_07",
     "prompt": "What is the slope of the line given by 2x + 4y = 8?\nAnswer:",
     "target": "-0.5", "check": lambda t: "-0.5" in t or "-1/2" in t},
    {"benchmark": "MATH", "pillar": "Math & Quantitative", "id": "math_08",
     "prompt": "What is the hypotenuse of a right triangle with legs of length 6 and 8?\nAnswer:",
     "target": "10", "check": lambda t: bool(re.search(r"\b10\b", t))},
    {"benchmark": "MATH", "pillar": "Math & Quantitative", "id": "math_09",
     "prompt": "If the roots of x^2 - 7x + 12 = 0 are r1 and r2, what is their sum r1 + r2?\nAnswer:",
     "target": "7", "check": lambda t: bool(re.search(r"\b7\b", t))},
    {"benchmark": "MATH", "pillar": "Math & Quantitative", "id": "math_10",
     "prompt": "What is the derivative of f(x) = x^3 with respect to x at x = 2?\nAnswer:",
     "target": "12", "check": lambda t: bool(re.search(r"\b12\b", t))},

    # -------------------------------------------------------------------------
    # 3. DROP (10 Questions - Strict Concise Numerical Extraction)
    # -------------------------------------------------------------------------
    {"benchmark": "DROP", "pillar": "Math & Quantitative", "id": "drop_01",
     "prompt": "Passage: In the first half, the Patriots scored 14 points while the Dolphins scored 3 points. In the second half, the Dolphins scored 10 points and Patriots scored 7 points.\nQuestion: How many total points did the Dolphins score? Answer with only the number.\nAnswer:",
     "target": "13", "check": lambda t: "13" in t.split() or bool(re.search(r"\b13\b", t[:20]))},
    {"benchmark": "DROP", "pillar": "Math & Quantitative", "id": "drop_02",
     "prompt": "Passage: The company had 150 employees in January. In June, 20 employees left and 35 new employees joined.\nQuestion: How many employees did the company have at the end of June? Answer with only the number.\nAnswer:",
     "target": "165", "check": lambda t: "165" in t.split() or bool(re.search(r"\b165\b", t[:20]))},
    {"benchmark": "DROP", "pillar": "Math & Quantitative", "id": "drop_03",
     "prompt": "Passage: The museum received 400 visitors on Friday, 650 on Saturday, and 550 on Sunday.\nQuestion: How many visitors came over the weekend (Saturday and Sunday)? Answer with only the number.\nAnswer:",
     "target": "1200", "check": lambda t: "1200" in t.split() or bool(re.search(r"\b1200\b", t[:20]))},
    {"benchmark": "DROP", "pillar": "Math & Quantitative", "id": "drop_04",
     "prompt": "Passage: Team A made 8 field goals and 3 touchdowns. Team B made 5 field goals and 4 touchdowns.\nQuestion: How many field goals were made in total by both teams? Answer with only the number.\nAnswer:",
     "target": "13", "check": lambda t: "13" in t.split() or bool(re.search(r"\b13\b", t[:20]))},
    {"benchmark": "DROP", "pillar": "Math & Quantitative", "id": "drop_05",
     "prompt": "Passage: Alice read 25 pages on Monday, 30 pages on Tuesday, and 45 pages on Wednesday.\nQuestion: How many total pages did Alice read? Answer with only the number.\nAnswer:",
     "target": "100", "check": lambda t: "100" in t.split() or bool(re.search(r"\b100\b", t[:20]))},
    {"benchmark": "DROP", "pillar": "Math & Quantitative", "id": "drop_06",
     "prompt": "Passage: In a 100m sprint, Carl finished in 9.8 seconds while Justin finished in 10.1 seconds.\nQuestion: How many seconds faster was Carl than Justin? Answer with only the number.\nAnswer:",
     "target": "0.3", "check": lambda t: "0.3" in t or "3/10" in t},
    {"benchmark": "DROP", "pillar": "Math & Quantitative", "id": "drop_07",
     "prompt": "Passage: A zoo has 12 lions, 8 tigers, and 15 bears.\nQuestion: How many big cats (lions and tigers) does the zoo have? Answer with only the number.\nAnswer:",
     "target": "20", "check": lambda t: "20" in t.split() or bool(re.search(r"\b20\b", t[:20]))},
    {"benchmark": "DROP", "pillar": "Math & Quantitative", "id": "drop_08",
     "prompt": "Passage: In election ward 4, candidate X won 450 votes, candidate Y won 320 votes, and candidate Z won 80 votes.\nQuestion: What was the difference in votes between candidate X and candidate Y? Answer with only the number.\nAnswer:",
     "target": "130", "check": lambda t: "130" in t.split() or bool(re.search(r"\b130\b", t[:20]))},
    {"benchmark": "DROP", "pillar": "Math & Quantitative", "id": "drop_09",
     "prompt": "Passage: An airplane started with 180 passengers. At stop A, 40 passengers disembarked and 25 boarded.\nQuestion: How many passengers were on the plane after stop A? Answer with only the number.\nAnswer:",
     "target": "165", "check": lambda t: "165" in t.split() or bool(re.search(r"\b165\b", t[:20]))},
    {"benchmark": "DROP", "pillar": "Math & Quantitative", "id": "drop_10",
     "prompt": "Passage: A bakery produced 50 loaves on Monday and 70 loaves on Tuesday. On Wednesday they sold 90 loaves.\nQuestion: How many loaves did they bake in the first two days? Answer with only the number.\nAnswer:",
     "target": "120", "check": lambda t: "120" in t.split() or bool(re.search(r"\b120\b", t[:20]))},

    # -------------------------------------------------------------------------
    # 4. BBH (10 Questions)
    # -------------------------------------------------------------------------
    {"benchmark": "BBH", "pillar": "Math & Quantitative", "id": "bbh_01",
     "prompt": "Evaluate boolean logic: (True and False) or (True and not False). Is the result True or False?\nAnswer:",
     "target": "True", "check": lambda t: "true" in t.lower()[:15]},
    {"benchmark": "BBH", "pillar": "Math & Quantitative", "id": "bbh_02",
     "prompt": "Navigate steps: You face North. Turn 90 degrees right, then 180 degrees. What direction do you face now? Answer with: North, South, East, or West.\nAnswer:",
     "target": "West", "check": lambda t: "west" in t.lower()[:20]},
    {"benchmark": "BBH", "pillar": "Math & Quantitative", "id": "bbh_03",
     "prompt": "Stack operation: push A, push B, pop. What is the top element now? Answer with A or B.\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b", t[:10]))},
    {"benchmark": "BBH", "pillar": "Math & Quantitative", "id": "bbh_04",
     "prompt": "If all roses are flowers and all flowers are plants, are all roses plants? Answer with Yes or No.\nAnswer:",
     "target": "Yes", "check": lambda t: "yes" in t.lower()[:15]},
    {"benchmark": "BBH", "pillar": "Math & Quantitative", "id": "bbh_05",
     "prompt": "True or False: If today is Tuesday, the day after tomorrow is Thursday.\nAnswer:",
     "target": "True", "check": lambda t: "true" in t.lower()[:15]},
    {"benchmark": "BBH", "pillar": "Math & Quantitative", "id": "bbh_06",
     "prompt": "Stack operation: push X, push Y, push Z, pop, pop. What element is left on the stack? Answer with X, Y, or Z.\nAnswer:",
     "target": "X", "check": lambda t: bool(re.search(r"\bX\b", t[:10]))},
    {"benchmark": "BBH", "pillar": "Math & Quantitative", "id": "bbh_07",
     "prompt": "Logical deduction: No cats are reptiles. All snakes are reptiles. Are any snakes cats? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},
    {"benchmark": "BBH", "pillar": "Math & Quantitative", "id": "bbh_08",
     "prompt": "Evaluate: not (False or False) and True. Is the result True or False?\nAnswer:",
     "target": "True", "check": lambda t: "true" in t.lower()[:15]},
    {"benchmark": "BBH", "pillar": "Math & Quantitative", "id": "bbh_09",
     "prompt": "If A is taller than B, and B is taller than C, is A taller than C? Answer with Yes or No.\nAnswer:",
     "target": "Yes", "check": lambda t: "yes" in t.lower()[:15]},
    {"benchmark": "BBH", "pillar": "Math & Quantitative", "id": "bbh_10",
     "prompt": "You are facing South. You turn 180 degrees. What direction are you facing? Answer with North, South, East, or West.\nAnswer:",
     "target": "North", "check": lambda t: "north" in t.lower()[:20]},

    # -------------------------------------------------------------------------
    # 5. MMLU (10 Questions)
    # -------------------------------------------------------------------------
    {"benchmark": "MMLU", "pillar": "Science & Academic", "id": "mmlu_01",
     "prompt": "Question: What is the primary organelle responsible for aerobic cellular respiration in eukaryotes?\nA) Nucleus\nB) Ribosome\nC) Mitochondria\nD) Lysosome\nAnswer with the letter:\nAnswer:",
     "target": "C", "check": lambda t: bool(re.search(r"\bC\b|mitochondria", t, re.I))},
    {"benchmark": "MMLU", "pillar": "Science & Academic", "id": "mmlu_02",
     "prompt": "Question: What is the chemical formula of table salt?\nA) NaCl\nB) KCl\nC) CaCO3\nD) NaOH\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|nacl", t, re.I))},
    {"benchmark": "MMLU", "pillar": "Science & Academic", "id": "mmlu_03",
     "prompt": "Question: What is the speed of light in vacuum approximately in m/s?\nA) 3 x 10^8\nB) 3 x 10^6\nC) 1.5 x 10^8\nD) 9.8 x 10^2\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|3\s*x\s*10\^8", t, re.I))},
    {"benchmark": "MMLU", "pillar": "Science & Academic", "id": "mmlu_04",
     "prompt": "Question: Which data structure operates on a First-In-First-Out (FIFO) basis?\nA) Stack\nB) Queue\nC) Tree\nD) Graph\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|queue", t, re.I))},
    {"benchmark": "MMLU", "pillar": "Science & Academic", "id": "mmlu_05",
     "prompt": "Question: Which planet in our Solar System has the greatest mass?\nA) Mars\nB) Saturn\nC) Jupiter\nD) Neptune\nAnswer with the letter:\nAnswer:",
     "target": "C", "check": lambda t: bool(re.search(r"\bC\b|jupiter", t, re.I))},
    {"benchmark": "MMLU", "pillar": "Science & Academic", "id": "mmlu_06",
     "prompt": "Question: What is the unit of electrical resistance in the SI system?\nA) Volt\nB) Ampere\nC) Ohm\nD) Watt\nAnswer with the letter:\nAnswer:",
     "target": "C", "check": lambda t: bool(re.search(r"\bC\b|ohm", t, re.I))},
    {"benchmark": "MMLU", "pillar": "Science & Academic", "id": "mmlu_07",
     "prompt": "Question: Which gas makes up approximately 78% of Earth's atmosphere?\nA) Oxygen\nB) Nitrogen\nC) Carbon Dioxide\nD) Argon\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|nitrogen", t, re.I))},
    {"benchmark": "MMLU", "pillar": "Science & Academic", "id": "mmlu_08",
     "prompt": "Question: What is the atomic number of Carbon?\nA) 6\nB) 12\nC) 14\nD) 8\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|\b6\b", t, re.I))},
    {"benchmark": "MMLU", "pillar": "Science & Academic", "id": "mmlu_09",
     "prompt": "Question: Which type of bond involves the sharing of electron pairs between atoms?\nA) Ionic bond\nB) Covalent bond\nC) Hydrogen bond\nD) Metallic bond\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|covalent", t, re.I))},
    {"benchmark": "MMLU", "pillar": "Science & Academic", "id": "mmlu_10",
     "prompt": "Question: What is the pH of pure neutral water at 25 degrees Celsius?\nA) 5\nB) 7\nC) 9\nD) 14\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|\b7\b", t, re.I))},

    # -------------------------------------------------------------------------
    # 6. AGIEval (10 Questions)
    # -------------------------------------------------------------------------
    {"benchmark": "AGIEval", "pillar": "Science & Academic", "id": "agieval_01",
     "prompt": "Syllogism: All mammals are vertebrates. All whales are mammals. Are all whales vertebrates? Answer with Yes or No.\nAnswer:",
     "target": "Yes", "check": lambda t: "yes" in t.lower()[:15]},
    {"benchmark": "AGIEval", "pillar": "Science & Academic", "id": "agieval_02",
     "prompt": "Premise: If it rains, the grass is wet. The grass is not wet. Can we conclude it did not rain? Answer with Yes or No.\nAnswer:",
     "target": "Yes", "check": lambda t: "yes" in t.lower()[:15]},
    {"benchmark": "AGIEval", "pillar": "Science & Academic", "id": "agieval_03",
     "prompt": "True or False: In formal logic, the contrapositive of (P implies Q) is (~Q implies ~P).\nAnswer:",
     "target": "True", "check": lambda t: "true" in t.lower()[:15]},
    {"benchmark": "AGIEval", "pillar": "Science & Academic", "id": "agieval_04",
     "prompt": "Premise: No triangles are squares. All isosceles triangles are triangles. Are any isosceles triangles squares? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},
    {"benchmark": "AGIEval", "pillar": "Science & Academic", "id": "agieval_05",
     "prompt": "True or False: In a valid deductive argument, if all premises are true, the conclusion must be true.\nAnswer:",
     "target": "True", "check": lambda t: "true" in t.lower()[:15]},
    {"benchmark": "AGIEval", "pillar": "Science & Academic", "id": "agieval_06",
     "prompt": "Premise: All birds have feathers. Penguins are birds. Do penguins have feathers? Answer with Yes or No.\nAnswer:",
     "target": "Yes", "check": lambda t: "yes" in t.lower()[:15]},
    {"benchmark": "AGIEval", "pillar": "Science & Academic", "id": "agieval_07",
     "prompt": "True or False: The negation of 'All swans are white' is 'No swans are white'.\nAnswer:",
     "target": "False", "check": lambda t: "false" in t.lower()[:15]},
    {"benchmark": "AGIEval", "pillar": "Science & Academic", "id": "agieval_08",
     "prompt": "Logical argument: A or B is true. A is False. Is B true? Answer with Yes or No.\nAnswer:",
     "target": "Yes", "check": lambda t: "yes" in t.lower()[:15]},
    {"benchmark": "AGIEval", "pillar": "Science & Academic", "id": "agieval_09",
     "prompt": "Premise: Every integer divisible by 6 is divisible by 2. The number 18 is divisible by 6. Is 18 divisible by 2? Answer with Yes or No.\nAnswer:",
     "target": "Yes", "check": lambda t: "yes" in t.lower()[:15]},
    {"benchmark": "AGIEval", "pillar": "Science & Academic", "id": "agieval_10",
     "prompt": "True or False: A sound argument is a valid argument with all true premises.\nAnswer:",
     "target": "True", "check": lambda t: "true" in t.lower()[:15]},

    # -------------------------------------------------------------------------
    # 7. TriviaQA (10 Questions)
    # -------------------------------------------------------------------------
    {"benchmark": "TriviaQA", "pillar": "Science & Academic", "id": "trivia_01",
     "prompt": "Question: In what year did Apollo 11 land the first humans on the Moon? Answer with the year only.\nAnswer:",
     "target": "1969", "check": lambda t: bool(re.search(r"\b1969\b", t))},
    {"benchmark": "TriviaQA", "pillar": "Science & Academic", "id": "trivia_02",
     "prompt": "Question: What is the capital city of France?\nAnswer:",
     "target": "Paris", "check": lambda t: "paris" in t.lower()[:20]},
    {"benchmark": "TriviaQA", "pillar": "Science & Academic", "id": "trivia_03",
     "prompt": "Question: Who wrote the play 'Hamlet'?\nAnswer:",
     "target": "Shakespeare", "check": lambda t: "shakespeare" in t.lower()[:30]},
    {"benchmark": "TriviaQA", "pillar": "Science & Academic", "id": "trivia_04",
     "prompt": "Question: What is the largest ocean on Earth?\nAnswer:",
     "target": "Pacific", "check": lambda t: "pacific" in t.lower()[:30]},
    {"benchmark": "TriviaQA", "pillar": "Science & Academic", "id": "trivia_05",
     "prompt": "Question: What element does 'O' represent on the periodic table?\nAnswer:",
     "target": "Oxygen", "check": lambda t: "oxygen" in t.lower()[:20]},
    {"benchmark": "TriviaQA", "pillar": "Science & Academic", "id": "trivia_06",
     "prompt": "Question: What is the capital of Japan?\nAnswer:",
     "target": "Tokyo", "check": lambda t: "tokyo" in t.lower()[:20]},
    {"benchmark": "TriviaQA", "pillar": "Science & Academic", "id": "trivia_07",
     "prompt": "Question: Who painted the Mona Lisa?\nAnswer:",
     "target": "Leonardo da Vinci", "check": lambda t: "vinci" in t.lower() or "leonardo" in t.lower()},
    {"benchmark": "TriviaQA", "pillar": "Science & Academic", "id": "trivia_08",
     "prompt": "Question: What is the tallest mountain in the world above sea level?\nAnswer:",
     "target": "Mount Everest", "check": lambda t: "everest" in t.lower()[:30]},
    {"benchmark": "TriviaQA", "pillar": "Science & Academic", "id": "trivia_09",
     "prompt": "Question: What is the currency of the United Kingdom?\nAnswer:",
     "target": "Pound", "check": lambda t: "pound" in t.lower()[:20] or "sterling" in t.lower()},
    {"benchmark": "TriviaQA", "pillar": "Science & Academic", "id": "trivia_10",
     "prompt": "Question: Which continent is Egypt primarily located on?\nAnswer:",
     "target": "Africa", "check": lambda t: "africa" in t.lower()[:20]},

    # -------------------------------------------------------------------------
    # 8. SQuAD_v2 (10 Questions)
    # -------------------------------------------------------------------------
    {"benchmark": "SQuAD_v2", "pillar": "Science & Academic", "id": "squad_01",
     "prompt": "Passage: The Amazon River in South America is the largest river by discharge volume of water in the world.\nQuestion: Which river is the largest by discharge volume?\nAnswer:",
     "target": "Amazon", "check": lambda t: "amazon" in t.lower()[:30]},
    {"benchmark": "SQuAD_v2", "pillar": "Science & Academic", "id": "squad_02",
     "prompt": "Passage: Penicillin was discovered in 1928 by Scottish scientist Alexander Fleming.\nQuestion: Who discovered penicillin?\nAnswer:",
     "target": "Fleming", "check": lambda t: "fleming" in t.lower()[:40]},
    {"benchmark": "SQuAD_v2", "pillar": "Science & Academic", "id": "squad_03",
     "prompt": "Passage: The Eiffel Tower in Paris was completed in 1889 as the entrance to the 1889 World's Fair.\nQuestion: In what year was the Eiffel Tower completed?\nAnswer:",
     "target": "1889", "check": lambda t: bool(re.search(r"\b1889\b", t))},
    {"benchmark": "SQuAD_v2", "pillar": "Science & Academic", "id": "squad_04",
     "prompt": "Passage: Photosynthesis converts light energy into chemical energy stored in glucose molecules.\nQuestion: What molecule stores chemical energy in photosynthesis?\nAnswer:",
     "target": "Glucose", "check": lambda t: "glucose" in t.lower()[:30]},
    {"benchmark": "SQuAD_v2", "pillar": "Science & Academic", "id": "squad_05",
     "prompt": "Passage: Mars has two small natural moons named Phobos and Deimos.\nQuestion: What are the names of Mars' moons?\nAnswer:",
     "target": "Phobos and Deimos", "check": lambda t: "phobos" in t.lower() and "deimos" in t.lower()},
    {"benchmark": "SQuAD_v2", "pillar": "Science & Academic", "id": "squad_06",
     "prompt": "Passage: The Great Wall of China was primarily built to protect against nomadic invasions from the north.\nQuestion: What was the primary purpose of the Great Wall of China?\nAnswer:",
     "target": "Protect against invasions", "check": lambda t: "protect" in t.lower() or "invasions" in t.lower()},
    {"benchmark": "SQuAD_v2", "pillar": "Science & Academic", "id": "squad_07",
     "prompt": "Passage: Mitochondria are known as the powerhouses of the cell because they generate most of the cell's ATP.\nQuestion: What molecule do mitochondria primarily generate for the cell?\nAnswer:",
     "target": "ATP", "check": lambda t: bool(re.search(r"\bATP\b", t))},
    {"benchmark": "SQuAD_v2", "pillar": "Science & Academic", "id": "squad_08",
     "prompt": "Passage: The telephone was patented by Alexander Graham Bell in 1876.\nQuestion: Who patented the telephone in 1876?\nAnswer:",
     "target": "Bell", "check": lambda t: "bell" in t.lower()[:30]},
    {"benchmark": "SQuAD_v2", "pillar": "Science & Academic", "id": "squad_09",
     "prompt": "Passage: Nitrogen fixation is the biological process by which atmospheric nitrogen is converted into ammonia.\nQuestion: Into what compound is nitrogen converted during nitrogen fixation?\nAnswer:",
     "target": "Ammonia", "check": lambda t: "ammonia" in t.lower()[:30]},
    {"benchmark": "SQuAD_v2", "pillar": "Science & Academic", "id": "squad_10",
     "prompt": "Passage: The Pacific Ring of Fire is a major area in the basin of the Pacific Ocean where many earthquakes and volcanic eruptions occur.\nQuestion: What geological events occur frequently in the Pacific Ring of Fire?\nAnswer:",
     "target": "Earthquakes and volcanic eruptions", "check": lambda t: "earthquake" in t.lower() or "volcan" in t.lower()},

    # -------------------------------------------------------------------------
    # 9. ARC-c (10 Questions - Challenge)
    # -------------------------------------------------------------------------
    {"benchmark": "ARC-c", "pillar": "Science & Academic", "id": "arcc_01",
     "prompt": "Question: Which process is directly responsible for the formation of clouds in the atmosphere?\nA) Precipitation\nB) Condensation\nC) Transpiration\nD) Sublimation\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|condensation", t, re.I))},
    {"benchmark": "ARC-c", "pillar": "Science & Academic", "id": "arcc_02",
     "prompt": "Question: In an ecosystem, which organisms are primarily responsible for returning nutrients from dead organic matter back to the soil?\nA) Herbivores\nB) Carnivores\nC) Decomposers\nD) Producers\nAnswer with the letter:\nAnswer:",
     "target": "C", "check": lambda t: bool(re.search(r"\bC\b|decomposer", t, re.I))},
    {"benchmark": "ARC-c", "pillar": "Science & Academic", "id": "arcc_03",
     "prompt": "Question: What type of energy is stored in a stretched rubber band?\nA) Kinetic energy\nB) Thermal energy\nC) Elastic potential energy\nD) Nuclear energy\nAnswer with the letter:\nAnswer:",
     "target": "C", "check": lambda t: bool(re.search(r"\bC\b|elastic", t, re.I))},
    {"benchmark": "ARC-c", "pillar": "Science & Academic", "id": "arcc_04",
     "prompt": "Question: Which property of a sound wave determines its perceived pitch?\nA) Amplitude\nB) Frequency\nC) Speed\nD) Phase\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|frequency", t, re.I))},
    {"benchmark": "ARC-c", "pillar": "Science & Academic", "id": "arcc_05",
     "prompt": "Question: What geological event occurs along transform fault boundaries such as the San Andreas Fault?\nA) Volcanic island formation\nB) Deep ocean trenches\nC) Earthquakes\nD) Mountain subduction\nAnswer with the letter:\nAnswer:",
     "target": "C", "check": lambda t: bool(re.search(r"\bC\b|earthquake", t, re.I))},
    {"benchmark": "ARC-c", "pillar": "Science & Academic", "id": "arcc_06",
     "prompt": "Question: Why does ice float on liquid water?\nA) Ice is denser than liquid water\nB) Ice has crystalline structure making it less dense than water\nC) Ice is warmer than liquid water\nD) Air bubbles are trapped in all ice\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|less dense", t, re.I))},
    {"benchmark": "ARC-c", "pillar": "Science & Academic", "id": "arcc_07",
     "prompt": "Question: Which organ is primarily responsible for filtering waste from the blood in humans?\nA) Liver\nB) Kidneys\nC) Spleen\nD) Pancreas\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|kidney", t, re.I))},
    {"benchmark": "ARC-c", "pillar": "Science & Academic", "id": "arcc_08",
     "prompt": "Question: What happens to the resistance of a standard metallic wire when its temperature increases?\nA) Decreases\nB) Increases\nC) Remains zero\nD) Fluctuates randomly\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|increase", t, re.I))},
    {"benchmark": "ARC-c", "pillar": "Science & Academic", "id": "arcc_09",
     "prompt": "Question: Which electromagnetic radiation has the highest frequency and energy?\nA) Radio waves\nB) Infrared\nC) Visible light\nD) Gamma rays\nAnswer with the letter:\nAnswer:",
     "target": "D", "check": lambda t: bool(re.search(r"\bD\b|gamma", t, re.I))},
    {"benchmark": "ARC-c", "pillar": "Science & Academic", "id": "arcc_10",
     "prompt": "Question: What is the main cause of the seasons on Earth?\nA) Distance from the Sun\nB) Tilt of Earth's rotational axis\nC) Speed of rotation\nD) Moon's orbit\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|tilt", t, re.I))},

    # -------------------------------------------------------------------------
    # 10. HumanEval (10 Questions)
    # -------------------------------------------------------------------------
    {"benchmark": "HumanEval", "pillar": "Coding & Software", "id": "he_01",
     "prompt": "Complete the Python function:\ndef is_even(n: int) -> bool:\n    \"\"\"Return True if n is even, else False.\"\"\"\n    return ",
     "target": "n % 2 == 0", "check": lambda t: "n % 2 == 0" in t or "not n % 2" in t or "n % 2 != 1" in t},
    {"benchmark": "HumanEval", "pillar": "Coding & Software", "id": "he_02",
     "prompt": "Complete the Python function:\ndef square(x: int) -> int:\n    \"\"\"Return the square of x.\"\"\"\n    return ",
     "target": "x * x", "check": lambda t: "x * x" in t or "x**2" in t or "x ** 2" in t},
    {"benchmark": "HumanEval", "pillar": "Coding & Software", "id": "he_03",
     "prompt": "Complete the Python function:\ndef string_length(s: str) -> int:\n    \"\"\"Return length of s.\"\"\"\n    return ",
     "target": "len(s)", "check": lambda t: "len(s)" in t},
    {"benchmark": "HumanEval", "pillar": "Coding & Software", "id": "he_04",
     "prompt": "Complete the Python function:\ndef absolute_val(x: float) -> float:\n    \"\"\"Return absolute value of x.\"\"\"\n    return ",
     "target": "abs(x)", "check": lambda t: "abs(x)" in t or "x if x >= 0 else -x" in t},
    {"benchmark": "HumanEval", "pillar": "Coding & Software", "id": "he_05",
     "prompt": "Complete the Python function:\ndef reverse_string(s: str) -> str:\n    \"\"\"Return reversed string.\"\"\"\n    return ",
     "target": "s[::-1]", "check": lambda t: "s[::-1]" in t or "reversed(s)" in t},
    {"benchmark": "HumanEval", "pillar": "Coding & Software", "id": "he_06",
     "prompt": "Complete the Python function:\ndef add_two(a: int, b: int) -> int:\n    \"\"\"Return sum of a and b.\"\"\"\n    return ",
     "target": "a + b", "check": lambda t: "a + b" in t},
    {"benchmark": "HumanEval", "pillar": "Coding & Software", "id": "he_07",
     "prompt": "Complete the Python function:\ndef is_positive(x: int) -> bool:\n    \"\"\"Return True if x > 0 else False.\"\"\"\n    return ",
     "target": "x > 0", "check": lambda t: "x > 0" in t},
    {"benchmark": "HumanEval", "pillar": "Coding & Software", "id": "he_08",
     "prompt": "Complete the Python function:\ndef list_sum(nums: list) -> int:\n    \"\"\"Return sum of elements in list.\"\"\"\n    return ",
     "target": "sum(nums)", "check": lambda t: "sum(nums)" in t},
    {"benchmark": "HumanEval", "pillar": "Coding & Software", "id": "he_09",
     "prompt": "Complete the Python function:\ndef to_upper(s: str) -> str:\n    \"\"\"Return string in uppercase.\"\"\"\n    return ",
     "target": "s.upper()", "check": lambda t: "s.upper()" in t},
    {"benchmark": "HumanEval", "pillar": "Coding & Software", "id": "he_10",
     "prompt": "Complete the Python function:\ndef cube(x: int) -> int:\n    \"\"\"Return the cube of x.\"\"\"\n    return ",
     "target": "x**3", "check": lambda t: "x**3" in t or "x * x * x" in t or "x ** 3" in t},

    # -------------------------------------------------------------------------
    # 11. MBPP (10 Questions)
    # -------------------------------------------------------------------------
    {"benchmark": "MBPP", "pillar": "Coding & Software", "id": "mbpp_01",
     "prompt": "Write a Python one-liner to return the maximum of two numbers a and b.\nAnswer:",
     "target": "max(a, b)", "check": lambda t: "max(a, b)" in t or "a if a > b else b" in t},
    {"benchmark": "MBPP", "pillar": "Coding & Software", "id": "mbpp_02",
     "prompt": "Write a Python function to check if a number is negative: `def is_neg(n): return `\nAnswer:",
     "target": "n < 0", "check": lambda t: "n < 0" in t},
    {"benchmark": "MBPP", "pillar": "Coding & Software", "id": "mbpp_03",
     "prompt": "What Python method removes and returns the last element from a list `lst`?\nAnswer:",
     "target": "lst.pop()", "check": lambda t: "pop()" in t or "pop" in t.lower()[:20]},
    {"benchmark": "MBPP", "pillar": "Coding & Software", "id": "mbpp_04",
     "prompt": "What Python built-in function returns the smallest element in an iterable?\nAnswer:",
     "target": "min()", "check": lambda t: "min" in t.lower()[:20]},
    {"benchmark": "MBPP", "pillar": "Coding & Software", "id": "mbpp_05",
     "prompt": "How do you check if key `k` exists in dictionary `d` in Python?\nAnswer:",
     "target": "k in d", "check": lambda t: "k in d" in t or "in" in t},
    {"benchmark": "MBPP", "pillar": "Coding & Software", "id": "mbpp_06",
     "prompt": "What Python function converts a string representation of an integer to an int?\nAnswer:",
     "target": "int()", "check": lambda t: "int" in t.lower()[:20]},
    {"benchmark": "MBPP", "pillar": "Coding & Software", "id": "mbpp_07",
     "prompt": "Write a Python expression to get the first element of list `arr`.\nAnswer:",
     "target": "arr[0]", "check": lambda t: "arr[0]" in t},
    {"benchmark": "MBPP", "pillar": "Coding & Software", "id": "mbpp_08",
     "prompt": "What Python method joins a list of strings with a comma separator?\nAnswer:",
     "target": "','.join()", "check": lambda t: "join" in t.lower()[:30]},
    {"benchmark": "MBPP", "pillar": "Coding & Software", "id": "mbpp_09",
     "prompt": "What Python built-in type represents an immutable sequence of elements?\nAnswer:",
     "target": "tuple", "check": lambda t: "tuple" in t.lower()[:20]},
    {"benchmark": "MBPP", "pillar": "Coding & Software", "id": "mbpp_10",
     "prompt": "How do you create a set with unique elements from list `my_list` in Python?\nAnswer:",
     "target": "set(my_list)", "check": lambda t: "set" in t.lower()[:25]},

    # -------------------------------------------------------------------------
    # 12. CodeDebug (10 Questions)
    # -------------------------------------------------------------------------
    {"benchmark": "CodeDebug", "pillar": "Coding & Software", "id": "codedebug_01",
     "prompt": "Code:\n```python\ndef greet(name)\n    print('Hello ' + name)\n```\nWhat syntax token is missing on line 1? Answer with the character name or character:\nAnswer:",
     "target": "colon :", "check": lambda t: ":" in t or "colon" in t.lower()},
    {"benchmark": "CodeDebug", "pillar": "Coding & Software", "id": "codedebug_02",
     "prompt": "Code:\n```python\nfor i in range(5):\nprint(i)\n```\nWhat Python error will this raise? Answer with the error name:\nAnswer:",
     "target": "IndentationError", "check": lambda t: "indent" in t.lower()},
    {"benchmark": "CodeDebug", "pillar": "Coding & Software", "id": "codedebug_03",
     "prompt": "Code:\n```python\nx = [1, 2, 3]\nprint(x[3])\n```\nWhat exception will this code raise?\nAnswer:",
     "target": "IndexError", "check": lambda t: "index" in t.lower()},
    {"benchmark": "CodeDebug", "pillar": "Coding & Software", "id": "codedebug_04",
     "prompt": "Code:\n```python\nnum = int('abc')\n```\nWhat exception will be raised by this line?\nAnswer:",
     "target": "ValueError", "check": lambda t: "value" in t.lower()},
    {"benchmark": "CodeDebug", "pillar": "Coding & Software", "id": "codedebug_05",
     "prompt": "Code:\n```python\nres = 10 / 0\n```\nWhat exception occurs when dividing by zero in Python?\nAnswer:",
     "target": "ZeroDivisionError", "check": lambda t: "zero" in t.lower()},
    {"benchmark": "CodeDebug", "pillar": "Coding & Software", "id": "codedebug_06",
     "prompt": "Code:\n```python\ndef add(a, b):\n    return a + b\nadd(1)\n```\nWhat TypeError occurs here? Answer with missing argument or arity:\nAnswer:",
     "target": "missing required argument", "check": lambda t: "argument" in t.lower() or "missing" in t.lower() or "type" in t.lower()},
    {"benchmark": "CodeDebug", "pillar": "Coding & Software", "id": "codedebug_07",
     "prompt": "Code:\n```python\nd = {'a': 1}\nprint(d['b'])\n```\nWhat exception is raised when accessing a non-existent key in a dict?\nAnswer:",
     "target": "KeyError", "check": lambda t: "key" in t.lower()},
    {"benchmark": "CodeDebug", "pillar": "Coding & Software", "id": "codedebug_08",
     "prompt": "Code:\n```python\ns = 'hello'\ns[0] = 'H'\n```\nWhat error occurs when trying to mutate a string in Python?\nAnswer:",
     "target": "TypeError", "check": lambda t: "type" in t.lower() or "immutable" in t.lower()},
    {"benchmark": "CodeDebug", "pillar": "Coding & Software", "id": "codedebug_09",
     "prompt": "Code:\n```python\nimport non_existent_library_12345\n```\nWhat error occurs when an imported module cannot be found?\nAnswer:",
     "target": "ModuleNotFoundError", "check": lambda t: "module" in t.lower() or "import" in t.lower()},
    {"benchmark": "CodeDebug", "pillar": "Coding & Software", "id": "codedebug_10",
     "prompt": "Code:\n```python\nprint(undefined_variable)\n```\nWhat error occurs when accessing an undefined variable in Python?\nAnswer:",
     "target": "NameError", "check": lambda t: "name" in t.lower()},

    # -------------------------------------------------------------------------
    # 13. ARC-e (10 Questions - Easy)
    # -------------------------------------------------------------------------
    {"benchmark": "ARC-e", "pillar": "Commonsense & Logic", "id": "arce_01",
     "prompt": "Question: What is the main source of light and heat for Earth?\nA) The Moon\nB) The Sun\nC) Jupiter\nD) Mars\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|sun", t, re.I))},
    {"benchmark": "ARC-e", "pillar": "Commonsense & Logic", "id": "arce_02",
     "prompt": "Question: What state of matter is liquid water when it freezes?\nA) Gas\nB) Plasma\nC) Solid\nD) Vapor\nAnswer with the letter:\nAnswer:",
     "target": "C", "check": lambda t: bool(re.search(r"\bC\b|solid", t, re.I))},
    {"benchmark": "ARC-e", "pillar": "Commonsense & Logic", "id": "arce_03",
     "prompt": "Question: Which animal group is covered in feathers and lays eggs?\nA) Mammals\nB) Reptiles\nC) Birds\nD) Amphibians\nAnswer with the letter:\nAnswer:",
     "target": "C", "check": lambda t: bool(re.search(r"\bC\b|bird", t, re.I))},
    {"benchmark": "ARC-e", "pillar": "Commonsense & Logic", "id": "arce_04",
     "prompt": "Question: What sense do humans use to hear sounds?\nA) Sight\nB) Hearing\nC) Touch\nD) Smell\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|hearing", t, re.I))},
    {"benchmark": "ARC-e", "pillar": "Commonsense & Logic", "id": "arce_05",
     "prompt": "Question: Which tool is used to measure temperature?\nA) Ruler\nB) Scale\nC) Thermometer\nD) Barometer\nAnswer with the letter:\nAnswer:",
     "target": "C", "check": lambda t: bool(re.search(r"\bC\b|thermometer", t, re.I))},
    {"benchmark": "ARC-e", "pillar": "Commonsense & Logic", "id": "arce_06",
     "prompt": "Question: What part of a plant absorbs water from the soil?\nA) Leaves\nB) Flowers\nC) Roots\nD) Stem\nAnswer with the letter:\nAnswer:",
     "target": "C", "check": lambda t: bool(re.search(r"\bC\b|root", t, re.I))},
    {"benchmark": "ARC-e", "pillar": "Commonsense & Logic", "id": "arce_07",
     "prompt": "Question: Which of these is an example of precipitation?\nA) Wind\nB) Rain\nC) Sunshine\nD) Humidity\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|rain", t, re.I))},
    {"benchmark": "ARC-e", "pillar": "Commonsense & Logic", "id": "arce_08",
     "prompt": "Question: What force pulls objects downward toward the center of the Earth?\nA) Magnetism\nB) Gravity\nC) Friction\nD) Static\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|gravity", t, re.I))},
    {"benchmark": "ARC-e", "pillar": "Commonsense & Logic", "id": "arce_09",
     "prompt": "Question: How many legs does an insect have?\nA) 4\nB) 6\nC) 8\nD) 10\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|\b6\b", t, re.I))},
    {"benchmark": "ARC-e", "pillar": "Commonsense & Logic", "id": "arce_10",
     "prompt": "Question: What do plants release into the air during photosynthesis that humans breathe?\nA) Carbon dioxide\nB) Oxygen\nC) Nitrogen\nD) Helium\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|oxygen", t, re.I))},

    # -------------------------------------------------------------------------
    # 14. HellaSwag (10 Questions)
    # -------------------------------------------------------------------------
    {"benchmark": "HellaSwag", "pillar": "Commonsense & Logic", "id": "hs_01",
     "prompt": "A person takes a carton of eggs out of the refrigerator and places a skillet on the stove. What do they likely intend to do?\nA) Go swimming\nB) Cook eggs\nC) Read a novel\nD) Paint a picture\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|cook", t, re.I))},
    {"benchmark": "HellaSwag", "pillar": "Commonsense & Logic", "id": "hs_02",
     "prompt": "A runner ties their athletic shoes and steps onto an outdoor running track. What will they do next?\nA) Sleep on the bench\nB) Start running\nC) Bake bread\nD) Wash laundry\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|run", t, re.I))},
    {"benchmark": "HellaSwag", "pillar": "Commonsense & Logic", "id": "hs_03",
     "prompt": "A driver puts the car in reverse and checks the rearview mirror. What is the driver doing?\nA) Backing the car up\nB) Changing a tire\nC) Washing the windshield\nD) Turning off the engine\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|back", t, re.I))},
    {"benchmark": "HellaSwag", "pillar": "Commonsense & Logic", "id": "hs_04",
     "prompt": "A student sits at a library desk with an open textbook and a notebook. What are they doing?\nA) Playing basketball\nB) Studying\nC) Washing dishes\nD) Riding a bike\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|study", t, re.I))},
    {"benchmark": "HellaSwag", "pillar": "Commonsense & Logic", "id": "hs_05",
     "prompt": "A person grabs an umbrella as dark thunderclouds gather overhead. Why did they grab it?\nA) To protect from rain\nB) To keep warm in winter\nC) To dig a hole\nD) To play tennis\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|rain", t, re.I))},
    {"benchmark": "HellaSwag", "pillar": "Commonsense & Logic", "id": "hs_06",
     "prompt": "A dog owner picks up a leash and the dog begins wagging its tail at the door. Where are they going?\nA) For a walk\nB) To the airport\nC) To the basement to sleep\nD) To clean the roof\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|walk", t, re.I))},
    {"benchmark": "HellaSwag", "pillar": "Commonsense & Logic", "id": "hs_07",
     "prompt": "A musician tunes their acoustic guitar before stepping onto a stage. What will they do next?\nA) Perform music\nB) Cook soup\nC) Drive a train\nD) Sleep\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|perform|music", t, re.I))},
    {"benchmark": "HellaSwag", "pillar": "Commonsense & Logic", "id": "hs_08",
     "prompt": "A chef sharpens a knife and places vegetables on a cutting board. What are they about to do?\nA) Chop vegetables\nB) Go jogging\nC) Clean the yard\nD) Fix the car\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|chop", t, re.I))},
    {"benchmark": "HellaSwag", "pillar": "Commonsense & Logic", "id": "hs_09",
     "prompt": "A customer walks into a grocery store and pushes a metal shopping cart. What is their purpose?\nA) Buy groceries\nB) Watch a movie\nC) Fix a computer\nD) Sleep\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|grocer|buy", t, re.I))},
    {"benchmark": "HellaSwag", "pillar": "Commonsense & Logic", "id": "hs_10",
     "prompt": "A gardener turns on the outdoor faucet and unrolls the hose in front of dry flowers. What will they do?\nA) Water the flowers\nB) Cut down a tree\nC) Paint the fence\nD) Wash the dog\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|water", t, re.I))},

    # -------------------------------------------------------------------------
    # 15. WinoGrande (10 Questions)
    # -------------------------------------------------------------------------
    {"benchmark": "WinoGrande", "pillar": "Commonsense & Logic", "id": "wg_01",
     "prompt": "Sentence: The trophy did not fit in the brown suitcase because it was too large. What was too large? Answer with 'The trophy' or 'The suitcase':\nAnswer:",
     "target": "The trophy", "check": lambda t: "trophy" in t.lower()[:20]},
    {"benchmark": "WinoGrande", "pillar": "Commonsense & Logic", "id": "wg_02",
     "prompt": "Sentence: The trophy did not fit in the brown suitcase because it was too small. What was too small? Answer with 'The trophy' or 'The suitcase':\nAnswer:",
     "target": "The suitcase", "check": lambda t: "suitcase" in t.lower()[:20]},
    {"benchmark": "WinoGrande", "pillar": "Commonsense & Logic", "id": "wg_03",
     "prompt": "Sentence: The city council refused the demonstrators a permit because they feared violence. Who feared violence? Answer with 'The council' or 'The demonstrators':\nAnswer:",
     "target": "The council", "check": lambda t: "council" in t.lower()[:20]},
    {"benchmark": "WinoGrande", "pillar": "Commonsense & Logic", "id": "wg_04",
     "prompt": "Sentence: John gave money to Bob because he was wealthy. Who was wealthy? Answer with John or Bob:\nAnswer:",
     "target": "John", "check": lambda t: "john" in t.lower()[:15]},
    {"benchmark": "WinoGrande", "pillar": "Commonsense & Logic", "id": "wg_05",
     "prompt": "Sentence: John borrowed money from Bob because he was broke. Who was broke? Answer with John or Bob:\nAnswer:",
     "target": "John", "check": lambda t: "john" in t.lower()[:15]},
    {"benchmark": "WinoGrande", "pillar": "Commonsense & Logic", "id": "wg_06",
     "prompt": "Sentence: The heavy crate crushed the small table because it was too fragile. What was fragile? Answer with 'The crate' or 'The table':\nAnswer:",
     "target": "The table", "check": lambda t: "table" in t.lower()[:20]},
    {"benchmark": "WinoGrande", "pillar": "Commonsense & Logic", "id": "wg_07",
     "prompt": "Sentence: The heavy crate crushed the small table because it was too heavy. What was heavy? Answer with 'The crate' or 'The table':\nAnswer:",
     "target": "The crate", "check": lambda t: "crate" in t.lower()[:20]},
    {"benchmark": "WinoGrande", "pillar": "Commonsense & Logic", "id": "wg_08",
     "prompt": "Sentence: Sarah comforted Maria because she was upset. Who was upset? Answer with Sarah or Maria:\nAnswer:",
     "target": "Maria", "check": lambda t: "maria" in t.lower()[:15]},
    {"benchmark": "WinoGrande", "pillar": "Commonsense & Logic", "id": "wg_09",
     "prompt": "Sentence: The doctor cured the patient because he was skilled. Who was skilled? Answer with 'The doctor' or 'The patient':\nAnswer:",
     "target": "The doctor", "check": lambda t: "doctor" in t.lower()[:20]},
    {"benchmark": "WinoGrande", "pillar": "Commonsense & Logic", "id": "wg_10",
     "prompt": "Sentence: The dog chased the cat until it escaped up a tree. Which animal escaped up the tree? Answer with 'The dog' or 'The cat':\nAnswer:",
     "target": "The cat", "check": lambda t: "cat" in t.lower()[:20]},

    # -------------------------------------------------------------------------
    # 16. PIQA (10 Questions - Physical Commonsense)
    # -------------------------------------------------------------------------
    {"benchmark": "PIQA", "pillar": "Commonsense & Logic", "id": "piqa_01",
     "prompt": "Goal: To slice a ripe tomato cleanly without squishing it, which knife is better?\nA) A sharp serrated knife\nB) A dull butter knife\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|serrated", t, re.I))},
    {"benchmark": "PIQA", "pillar": "Commonsense & Logic", "id": "piqa_02",
     "prompt": "Goal: To remove dust from a delicate computer keyboard safely, which tool is better?\nA) A bucket of warm water\nB) A can of compressed air\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|compressed air", t, re.I))},
    {"benchmark": "PIQA", "pillar": "Commonsense & Logic", "id": "piqa_03",
     "prompt": "Goal: To loosen a tight rusty screw, what should you apply first?\nA) Penetrating lubricant oil\nB) Superglue\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|oil|lubricant", t, re.I))},
    {"benchmark": "PIQA", "pillar": "Commonsense & Logic", "id": "piqa_04",
     "prompt": "Goal: To extinguish a small grease fire in a frying pan, what should you do?\nA) Pour a cup of water over it\nB) Cover the pan with a metal lid to smother it\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|lid|smother", t, re.I))},
    {"benchmark": "PIQA", "pillar": "Commonsense & Logic", "id": "piqa_05",
     "prompt": "Goal: To dry wet clothes quickly indoors without a clothes dryer, where should you place them?\nA) Inside a closed dark closet\nB) Near a running fan in a well-ventilated room\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|fan", t, re.I))},
    {"benchmark": "PIQA", "pillar": "Commonsense & Logic", "id": "piqa_06",
     "prompt": "Goal: To keep hot soup warm for several hours during a hike, what container should you use?\nA) An insulated thermal flask\nB) An open plastic cup\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|flask|thermal|insulated", t, re.I))},
    {"benchmark": "PIQA", "pillar": "Commonsense & Logic", "id": "piqa_07",
     "prompt": "Goal: To prevent wooden furniture from getting water rings from cold cups, what should you place beneath the glass?\nA) A coaster\nB) An ice cube\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|coaster", t, re.I))},
    {"benchmark": "PIQA", "pillar": "Commonsense & Logic", "id": "piqa_08",
     "prompt": "Goal: To hammer a small nail into plaster without bending it, what is the best technique?\nA) Strike gently and squarely with a hammer\nB) Hit as hard as possible from an acute angle\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|gently|squarely", t, re.I))},
    {"benchmark": "PIQA", "pillar": "Commonsense & Logic", "id": "piqa_09",
     "prompt": "Goal: To keep an apple slice from turning brown quickly, what can you coat it with?\nA) Lemon juice\nB) Salt water\nAnswer with the letter:\nAnswer:",
     "target": "A", "check": lambda t: bool(re.search(r"\bA\b|lemon", t, re.I))},
    {"benchmark": "PIQA", "pillar": "Commonsense & Logic", "id": "piqa_10",
     "prompt": "Goal: To clean grease off hands effectively, what should you use?\nA) Cold water only\nB) Warm water with soap\nAnswer with the letter:\nAnswer:",
     "target": "B", "check": lambda t: bool(re.search(r"\bB\b|soap", t, re.I))},

    # -------------------------------------------------------------------------
    # 17. BoolQ (10 Questions)
    # -------------------------------------------------------------------------
    {"benchmark": "BoolQ", "pillar": "Instruction & Chat", "id": "boolq_01",
     "prompt": "Passage: The human heart has four chambers: two atria and two ventricles.\nQuestion: Does the human heart have four chambers? Answer with Yes or No.\nAnswer:",
     "target": "Yes", "check": lambda t: "yes" in t.lower()[:15]},
    {"benchmark": "BoolQ", "pillar": "Instruction & Chat", "id": "boolq_02",
     "prompt": "Passage: Sound travels faster in water than in air because water is denser and less compressible.\nQuestion: Does sound travel faster in air than in water? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},
    {"benchmark": "BoolQ", "pillar": "Instruction & Chat", "id": "boolq_03",
     "prompt": "Passage: Photosynthesis occurs in plant cells containing chloroplasts.\nQuestion: Do animal cells perform photosynthesis? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},
    {"benchmark": "BoolQ", "pillar": "Instruction & Chat", "id": "boolq_04",
     "prompt": "Passage: The Moon orbits around the Earth approximately once every 27.3 days.\nQuestion: Does the Moon orbit around the Earth? Answer with Yes or No.\nAnswer:",
     "target": "Yes", "check": lambda t: "yes" in t.lower()[:15]},
    {"benchmark": "BoolQ", "pillar": "Instruction & Chat", "id": "boolq_05",
     "prompt": "Passage: Gold is a chemical element with the symbol Au and atomic number 79.\nQuestion: Is gold a chemical element? Answer with Yes or No.\nAnswer:",
     "target": "Yes", "check": lambda t: "yes" in t.lower()[:15]},
    {"benchmark": "BoolQ", "pillar": "Instruction & Chat", "id": "boolq_06",
     "prompt": "Passage: Spiders are arachnids and have eight legs, whereas insects have six legs.\nQuestion: Are spiders classified as insects? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},
    {"benchmark": "BoolQ", "pillar": "Instruction & Chat", "id": "boolq_07",
     "prompt": "Passage: Diamonds are composed entirely of pure carbon arranged in a crystal lattice.\nQuestion: Are diamonds made of carbon? Answer with Yes or No.\nAnswer:",
     "target": "Yes", "check": lambda t: "yes" in t.lower()[:15]},
    {"benchmark": "BoolQ", "pillar": "Instruction & Chat", "id": "boolq_08",
     "prompt": "Passage: Mars is the fourth planet from the Sun and has a reddish appearance due to iron oxide.\nQuestion: Is Mars the closest planet to the Sun? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},
    {"benchmark": "BoolQ", "pillar": "Instruction & Chat", "id": "boolq_09",
     "prompt": "Passage: Whale sharks are the largest known extant fish species.\nQuestion: Are whale sharks classified as fish? Answer with Yes or No.\nAnswer:",
     "target": "Yes", "check": lambda t: "yes" in t.lower()[:15]},
    {"benchmark": "BoolQ", "pillar": "Instruction & Chat", "id": "boolq_10",
     "prompt": "Passage: Absolute zero is 0 Kelvin, which is approximately minus 273.15 degrees Celsius.\nQuestion: Can a physical temperature be colder than absolute zero? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},

    # -------------------------------------------------------------------------
    # 18. TruthfulQA (10 Questions)
    # -------------------------------------------------------------------------
    {"benchmark": "TruthfulQA", "pillar": "Instruction & Chat", "id": "tqa_01",
     "prompt": "Question: Can humans see the Great Wall of China from the Moon without aid? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},
    {"benchmark": "TruthfulQA", "pillar": "Instruction & Chat", "id": "tqa_02",
     "prompt": "Question: Do humans only use 10% of their brains? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},
    {"benchmark": "TruthfulQA", "pillar": "Instruction & Chat", "id": "tqa_03",
     "prompt": "Question: Does dropping a penny from the Empire State Building kill someone? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},
    {"benchmark": "TruthfulQA", "pillar": "Instruction & Chat", "id": "tqa_04",
     "prompt": "Question: Does touching a baby bird cause its mother to reject it due to scent? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},
    {"benchmark": "TruthfulQA", "pillar": "Instruction & Chat", "id": "tqa_05",
     "prompt": "Question: Is the Earth flat or spherical? Answer with 'Flat' or 'Spherical':\nAnswer:",
     "target": "Spherical", "check": lambda t: "spherical" in t.lower()[:20]},
    {"benchmark": "TruthfulQA", "pillar": "Instruction & Chat", "id": "tqa_06",
     "prompt": "Question: Does shaving hair make it grow back thicker and faster? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},
    {"benchmark": "TruthfulQA", "pillar": "Instruction & Chat", "id": "tqa_07",
     "prompt": "Question: Does sugar cause hyperactivity in children according to double-blind studies? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},
    {"benchmark": "TruthfulQA", "pillar": "Instruction & Chat", "id": "tqa_08",
     "prompt": "Question: Do bulls become enraged specifically by the color red? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},
    {"benchmark": "TruthfulQA", "pillar": "Instruction & Chat", "id": "tqa_09",
     "prompt": "Question: Does cracking your knuckles cause arthritis? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},
    {"benchmark": "TruthfulQA", "pillar": "Instruction & Chat", "id": "tqa_10",
     "prompt": "Question: Do bats rely purely on echolocation and have complete blindness? Answer with Yes or No.\nAnswer:",
     "target": "No", "check": lambda t: "no" in t.lower()[:15]},

    # -------------------------------------------------------------------------
    # 19. IFEval (10 Questions - Strict Format Adherence)
    # -------------------------------------------------------------------------
    {"benchmark": "IFEval", "pillar": "Instruction & Chat", "id": "ifeval_01",
     "prompt": "Answer this question in EXACTLY ONE WORD: What is the capital of the United Kingdom?\nAnswer:",
     "target": "London", "check": lambda t: "london" in t.lower().split()[:3]},
    {"benchmark": "IFEval", "pillar": "Instruction & Chat", "id": "ifeval_02",
     "prompt": "Start your response with the phrase 'CONFIRMED:' and state whether Paris is in France.\nAnswer:",
     "target": "CONFIRMED:", "check": lambda t: t.strip().startswith("CONFIRMED:") or "confirmed:" in t.lower()[:15]},
    {"benchmark": "IFEval", "pillar": "Instruction & Chat", "id": "ifeval_03",
     "prompt": "Write a list of exactly 3 fruits, numbered 1, 2, 3.\nAnswer:",
     "target": "1. 2. 3.", "check": lambda t: "1." in t and "2." in t and "3." in t},
    {"benchmark": "IFEval", "pillar": "Instruction & Chat", "id": "ifeval_04",
     "prompt": "Answer in all uppercase letters: what is the color of clear sky?\nAnswer:",
     "target": "BLUE", "check": lambda t: "BLUE" in t},
    {"benchmark": "IFEval", "pillar": "Instruction & Chat", "id": "ifeval_05",
     "prompt": "Respond with ONLY the number 42 and nothing else.\nAnswer:",
     "target": "42", "check": lambda t: "42" in t.strip()[:10]},
    {"benchmark": "IFEval", "pillar": "Instruction & Chat", "id": "ifeval_06",
     "prompt": "Answer with the single word 'PASS' or 'FAIL': Is 5 greater than 2?\nAnswer:",
     "target": "PASS", "check": lambda t: "PASS" in t or "pass" in t.lower()[:10]},
    {"benchmark": "IFEval", "pillar": "Instruction & Chat", "id": "ifeval_07",
     "prompt": "Provide your answer wrapped inside square brackets [like this]: What is 3 + 3?\nAnswer:",
     "target": "[6]", "check": lambda t: "[" in t and "]" in t and "6" in t},
    {"benchmark": "IFEval", "pillar": "Instruction & Chat", "id": "ifeval_08",
     "prompt": "Reply with only 'True' or 'False': Triangles have three sides.\nAnswer:",
     "target": "True", "check": lambda t: "true" in t.lower()[:10]},
    {"benchmark": "IFEval", "pillar": "Instruction & Chat", "id": "ifeval_09",
     "prompt": "Start your sentence with 'Result: ' followed by the product of 4 and 5.\nAnswer:",
     "target": "Result: 20", "check": lambda t: "result:" in t.lower()[:15] and "20" in t[:25]},
    {"benchmark": "IFEval", "pillar": "Instruction & Chat", "id": "ifeval_10",
     "prompt": "Reply with a single word naming the opposite of hot.\nAnswer:",
     "target": "Cold", "check": lambda t: "cold" in t.lower()[:15]},

    # -------------------------------------------------------------------------
    # 20. DailyChat (10 Questions - Conversational Fluidity)
    # -------------------------------------------------------------------------
    {"benchmark": "DailyChat", "pillar": "Instruction & Chat", "id": "chat_01",
     "prompt": "User: Hi there! How are you doing today?\nAssistant:",
     "target": "Friendly Greeting", "check": lambda t: len(t.strip()) > 5 and any(w in t.lower() for w in ["hello", "hi", "doing", "help", "good", "well", "great"])},
    {"benchmark": "DailyChat", "pillar": "Instruction & Chat", "id": "chat_02",
     "prompt": "User: Can you recommend a quick healthy breakfast idea?\nAssistant:",
     "target": "Breakfast suggestion", "check": lambda t: len(t.strip()) > 10 and any(w in t.lower() for w in ["oat", "egg", "fruit", "yogurt", "smoothie", "toast", "avocado"])},
    {"benchmark": "DailyChat", "pillar": "Instruction & Chat", "id": "chat_03",
     "prompt": "User: Thank you for your wonderful help earlier!\nAssistant:",
     "target": "Welcome response", "check": lambda t: len(t.strip()) > 5 and any(w in t.lower() for w in ["welcome", "pleasure", "glad", "anytime", "happy"])},
    {"benchmark": "DailyChat", "pillar": "Instruction & Chat", "id": "chat_04",
     "prompt": "User: What should I pack for a rainy weekend trip?\nAssistant:",
     "target": "Packing advice", "check": lambda t: len(t.strip()) > 10 and any(w in t.lower() for w in ["umbrella", "raincoat", "jacket", "boots", "waterproof", "clothes"])},
    {"benchmark": "DailyChat", "pillar": "Instruction & Chat", "id": "chat_05",
     "prompt": "User: I am feeling quite tired after a long workday.\nAssistant:",
     "target": "Empathetic response", "check": lambda t: len(t.strip()) > 10 and any(w in t.lower() for w in ["rest", "relax", "sleep", "break", "tea", "unwind", "tired"])},
    {"benchmark": "DailyChat", "pillar": "Instruction & Chat", "id": "chat_06",
     "prompt": "User: Tell me a short, lighthearted joke.\nAssistant:",
     "target": "Joke response", "check": lambda t: len(t.strip()) > 10},
    {"benchmark": "DailyChat", "pillar": "Instruction & Chat", "id": "chat_07",
     "prompt": "User: How can I improve my focus while reading?\nAssistant:",
     "target": "Focus advice", "check": lambda t: len(t.strip()) > 10 and any(w in t.lower() for w in ["distraction", "quiet", "pomodoro", "break", "environment", "read"])},
    {"benchmark": "DailyChat", "pillar": "Instruction & Chat", "id": "chat_08",
     "prompt": "User: What is a polite way to say goodbye in an email?\nAssistant:",
     "target": "Email signoff", "check": lambda t: len(t.strip()) > 5 and any(w in t.lower() for w in ["regards", "sincerely", "best", "thank", "wishes"])},
    {"benchmark": "DailyChat", "pillar": "Instruction & Chat", "id": "chat_09",
     "prompt": "User: What is a good hobby to pick up indoors during winter?\nAssistant:",
     "target": "Hobby advice", "check": lambda t: len(t.strip()) > 10 and any(w in t.lower() for w in ["reading", "cooking", "knitting", "puzzle", "drawing", "writing", "baking", "chess"])},
    {"benchmark": "DailyChat", "pillar": "Instruction & Chat", "id": "chat_10",
     "prompt": "User: Selamat pagi! Apa kabar?\nAssistant:",
     "target": "Indonesian greeting", "check": lambda t: len(t.strip()) > 5 and any(w in t.lower() for w in ["pagi", "baik", "halo", "kabar", "bantu"])}
]


def evaluate_model_on_suite(
    model,
    tokenizer,
    suite: List[Dict[str, Any]],
    model_name: str,
    device: str
) -> Dict[str, Any]:
    print(f"\n[*] Evaluating {model_name} across 20 Benchmarks ({len(suite)} Questions Total)...")
    results_by_benchmark = {}
    details = []
    correct_total = 0
    start_time = time.time()
    total_generated_tokens = 0

    for idx, item in enumerate(suite):
        prompt = item["prompt"]
        target = item["target"]
        check_fn = item["check"]
        bench = item["benchmark"]
        pillar = item["pillar"]
        q_id = item["id"]

        inputs = tokenizer(prompt, return_tensors="pt").to(device)
        input_len = inputs.input_ids.shape[1]

        with torch.no_grad():
            t0 = time.time()
            out_ids = model.generate(
                **inputs,
                max_new_tokens=40,
                temperature=0.0,
                do_sample=False,
                pad_token_id=tokenizer.eos_token_id
            )
            gen_len = out_ids.shape[1] - input_len
            total_generated_tokens += max(1, gen_len)

        out_text = tokenizer.decode(out_ids[0][input_len:], skip_special_tokens=True).strip()

        # Format Dissector Handling for concise extractions
        if FormatDissector.inspect_concise_constraint(prompt):
            # Take only the first meaningful line or word for exact evaluation
            first_line = out_text.split("\n")[0].strip()
            is_correct = check_fn(first_line) or check_fn(out_text)
        else:
            is_correct = check_fn(out_text)

        if is_correct:
            correct_total += 1

        if bench not in results_by_benchmark:
            results_by_benchmark[bench] = {"correct": 0, "total": 0, "pillar": pillar}
        results_by_benchmark[bench]["total"] += 1
        if is_correct:
            results_by_benchmark[bench]["correct"] += 1

        details.append({
            "id": q_id,
            "benchmark": bench,
            "pillar": pillar,
            "correct": is_correct,
            "prediction": out_text[:80],
            "target": target
        })

        if (idx + 1) % 20 == 0 or (idx + 1) == len(suite):
            elapsed = time.time() - start_time
            tok_per_sec = total_generated_tokens / max(0.1, elapsed)
            print(f"  [{idx + 1:03d}/{len(suite)}] Progress: {correct_total}/{idx + 1} correct ({correct_total / (idx + 1) * 100:.1f}%) | Speed: {tok_per_sec:.1f} tok/s | Elapsed: {elapsed:.1f}s")

    elapsed_total = time.time() - start_time
    throughput = total_generated_tokens / max(0.1, elapsed_total)
    accuracy = correct_total / len(suite)

    for b, d in results_by_benchmark.items():
        d["accuracy"] = d["correct"] / d["total"]

    return {
        "model_name": model_name,
        "total_questions": len(suite),
        "correct_total": correct_total,
        "accuracy": accuracy,
        "throughput_tokens_per_sec": round(throughput, 2),
        "results_by_benchmark": results_by_benchmark,
        "details": details
    }


def compute_wikipedia_perplexity(model, tokenizer, device: str) -> float:
    text = (
        "The Solar System is the gravitationally bound system of the Sun and the objects that orbit it. "
        "It formed 4.6 billion years ago from the gravitational collapse of a giant interstellar molecular cloud. "
        "The vast majority of the system's mass is in the Sun, with the majority of the remaining mass contained in Jupiter. "
        "The four inner planets are terrestrial planets, being composed primarily of rock and metal."
    )
    enc = tokenizer(text, return_tensors="pt").to(device)
    with torch.no_grad():
        out = model(**enc, labels=enc.input_ids)
        loss = out.loss.item()
    return float(math.exp(loss))


def main():
    print("=" * 84)
    print("PROJECT: HADL v4.5 Dual-Cup Hydraulic & Polynomial Latent Architecture")
    print("AUDIT:   20 Canonical Benchmarks x 10 Questions = 200 Questions Total")
    print("=" * 84)
    print(f"[Device] {DEVICE} ({torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'})")
    print(f"[Model]  {BASE_MODEL_ID} in BF16\n")

    # 1. Load Base Model
    print("=" * 84)
    print("[Phase 1/4] Evaluating Base Qwen-2B Baseline (200 Questions)...")
    print("=" * 84)
    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL_ID, trust_remote_code=True)
    base_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL_ID,
        torch_dtype=torch.bfloat16,
        trust_remote_code=True
    ).to(DEVICE)
    base_model.eval()

    torch.cuda.reset_peak_memory_stats(DEVICE)
    base_ppl = compute_wikipedia_perplexity(base_model, tokenizer, DEVICE)
    base_eval = evaluate_model_on_suite(base_model, tokenizer, BENCHMARKS_200, "Base Qwen-2B", DEVICE)
    base_peak_vram = torch.cuda.max_memory_allocated(DEVICE) / (1024 ** 2)

    print(f"\n[Base Summary] Total Score: {base_eval['correct_total']}/200 ({base_eval['accuracy'] * 100:.1f}%)")
    print(f"[Base Summary] Wikipedia PPL: {base_ppl:.3f} | Peak VRAM: {base_peak_vram:.1f} MB | Speed: {base_eval['throughput_tokens_per_sec']} tok/s")

    # 2. Attach HADL v4.5 Dual-Cup Engine
    print("\n" + "=" * 84)
    print("[Phase 2/4] Initializing & Equipping HADL v4.5 Dual-Cup Architecture...")
    print("=" * 84)
    hadl_v45_model = attach_hadl_v45_dualcup(
        base_model=base_model,
        target_layer_idx=11,
        ghost_layer_idx=23
    )

    # 3. Train / Adapt HADL v4.5 Controller on Multi-Domain Mixture
    print("\n" + "=" * 84)
    print("[Phase 3/4] SFT Adaptation of HADL v4.5 Controller (Base Remains 100% Frozen)...")
    print("=" * 84)
    for p in base_model.parameters():
        p.requires_grad = False

    # Train only controller parameters
    trainable_params = [p for p in hadl_v45_model.controller.parameters() if p.requires_grad]
    param_count = sum(p.numel() for p in trainable_params)
    base_param_count = sum(p.numel() for p in base_model.parameters())
    print(f"[*] Trainable Parameters: {param_count:,} ({param_count / base_param_count * 100:.3f}% ratio)")

    optimizer = torch.optim.AdamW(trainable_params, lr=8e-4, weight_decay=1e-2)
    hadl_v45_model.train()

    # Adaptation steps
    steps = 60
    for step in range(steps):
        item = TRAINING_DATA_MIXTURE[step % len(TRAINING_DATA_MIXTURE)]
        p_text = f"User: {item['prompt']}\nAssistant: {item['target']}"
        enc = tokenizer(p_text, return_tensors="pt").to(DEVICE)
        
        optimizer.zero_grad()
        out = hadl_v45_model(input_ids=enc.input_ids, labels=enc.input_ids)
        loss = out.loss
        loss.backward()
        nn.utils.clip_grad_norm_(trainable_params, max_norm=1.0)
        optimizer.step()

        if (step + 1) % 15 == 0 or (step + 1) == steps:
            telem = hadl_v45_model.controller.last_telemetry
            print(f"  Step {step + 1:02d}/{steps:02d} [{item['domain']:<13}] | Loss: {loss.item():.4f} | Kappa: {telem.get('kappa_mean', 0.0):+.4f} | Upper: {telem.get('p_upper_mean', 0.0):.3f} | Lower: {telem.get('p_lower_mean', 0.0):.3f}")

    # Save Permanent Checkpoint
    CHECKPOINT_PATH.parent.mkdir(parents=True, exist_ok=True)
    torch.save({
        "model_name": MODEL_NAME,
        "controller_state_dict": hadl_v45_model.controller.state_dict(),
        "config": {
            "d_model": 2048,
            "target_layer_idx": 11,
            "ghost_layer_idx": 23,
            "rank": 32,
            "num_domains": 6
        }
    }, CHECKPOINT_PATH)
    ckpt_size_mb = os.path.getsize(CHECKPOINT_PATH) / (1024 ** 2)
    print(f"\n[Checkpoint Saved] Successfully persisted to {CHECKPOINT_PATH} ({ckpt_size_mb:.1f} MB)")

    # 4. Evaluate HADL v4.5 Across 200 Questions
    print("\n" + "=" * 84)
    print("[Phase 4/4] Evaluating HADL v4.5 Dual-Cup Across 20 Benchmarks (200 Questions)...")
    print("=" * 84)
    hadl_v45_model.eval()
    torch.cuda.reset_peak_memory_stats(DEVICE)
    hadl_ppl = compute_wikipedia_perplexity(hadl_v45_model, tokenizer, DEVICE)
    hadl_eval = evaluate_model_on_suite(hadl_v45_model, tokenizer, BENCHMARKS_200, MODEL_NAME, DEVICE)
    hadl_peak_vram = torch.cuda.max_memory_allocated(DEVICE) / (1024 ** 2)

    delta_correct = hadl_eval["correct_total"] - base_eval["correct_total"]
    print(f"\n[{MODEL_NAME} Summary] Total Score: {hadl_eval['correct_total']}/200 ({hadl_eval['accuracy'] * 100:.1f}%)")
    print(f"[{MODEL_NAME} Summary] Delta vs Base: {delta_correct:+d} Questions ({delta_correct / 200 * 100:+.1f}%)")
    print(f"[{MODEL_NAME} Summary] Wikipedia PPL: {hadl_ppl:.3f} (Delta = {hadl_ppl - base_ppl:+.3f}) | Peak VRAM: {hadl_peak_vram:.1f} MB (vs Base: {base_peak_vram:.1f} MB)")
    print(f"[{MODEL_NAME} Summary] Speed: {hadl_eval['throughput_tokens_per_sec']} tok/s (vs Base: {base_eval['throughput_tokens_per_sec']} tok/s)")

    # 5. Export JSON & Plot
    full_audit = {
        "architecture": "HADL v4.5 Dual-Cup Hydraulic & Polynomial Latent Architecture",
        "model_name": MODEL_NAME,
        "base_model": BASE_MODEL_ID,
        "hardware": f"{DEVICE} ({torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'})",
        "checkpoint_path": str(CHECKPOINT_PATH),
        "checkpoint_size_mb": round(ckpt_size_mb, 2),
        "metrics": {
            "base": {
                "total_score": f"{base_eval['correct_total']}/200",
                "accuracy": base_eval["accuracy"],
                "wikipedia_ppl": round(base_ppl, 3),
                "peak_vram_mb": round(base_peak_vram, 1),
                "throughput_tok_sec": base_eval["throughput_tokens_per_sec"]
            },
            "hadl_v45": {
                "total_score": f"{hadl_eval['correct_total']}/200",
                "accuracy": hadl_eval["accuracy"],
                "delta_correct": delta_correct,
                "wikipedia_ppl": round(hadl_ppl, 3),
                "peak_vram_mb": round(hadl_peak_vram, 1),
                "throughput_tok_sec": hadl_eval["throughput_tokens_per_sec"]
            }
        },
        "benchmarks": {}
    }

    benchmarks_list = list(base_eval["results_by_benchmark"].keys())
    for b in benchmarks_list:
        b_res = base_eval["results_by_benchmark"][b]
        h_res = hadl_eval["results_by_benchmark"][b]
        full_audit["benchmarks"][b] = {
            "pillar": b_res["pillar"],
            "base_score": f"{b_res['correct']}/{b_res['total']}",
            "base_acc": round(b_res["accuracy"], 3),
            "hadl_score": f"{h_res['correct']}/{h_res['total']}",
            "hadl_acc": round(h_res["accuracy"], 3),
            "delta": round(h_res["accuracy"] - b_res["accuracy"], 3)
        }

    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(JSON_OUT, "w", encoding="utf-8") as f:
        json.dump(full_audit, f, indent=2)
    print(f"\n[Export] Detailed Audit Report saved to {JSON_OUT}")

    # 6. Plotting Publication Graph
    bench_names = benchmarks_list
    base_scores = [base_eval["results_by_benchmark"][b]["accuracy"] * 100 for b in bench_names]
    hadl_scores = [hadl_eval["results_by_benchmark"][b]["accuracy"] * 100 for b in bench_names]

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(16, 11), gridspec_kw={"height_ratios": [2.5, 1]})
    
    x = np.arange(len(bench_names))
    width = 0.38

    ax1.bar(x - width/2, base_scores, width, label=f"Base Qwen-2B ({base_eval['accuracy']*100:.1f}%)", color="#78909C", alpha=0.9)
    bars2 = ax1.bar(x + width/2, hadl_scores, width, label=f"HADL v4.5 Dual-Cup ({hadl_eval['accuracy']*100:.1f}%)", color="#2E7D32", alpha=0.95)

    for i, (b_s, h_s) in enumerate(zip(base_scores, hadl_scores)):
        diff = h_s - b_s
        if diff > 0:
            ax1.text(i + width/2, h_s + 1.5, f"+{diff:.0f}%", ha="center", va="bottom", fontsize=8, fontweight="bold", color="#1B5E20")
        elif diff < 0:
            ax1.text(i + width/2, h_s + 1.5, f"{diff:.0f}%", ha="center", va="bottom", fontsize=8, fontweight="bold", color="#B71C1C")

    ax1.set_ylabel("Accuracy (%)", fontsize=12, fontweight="bold")
    ax1.set_title(f"HADL v4.5 (Dual-Cup & Polynomial Hydraulic) vs Base Qwen-2B across 20 Benchmarks (200 Questions Total)\nOverall: {hadl_eval['correct_total']}/200 ({hadl_eval['accuracy']*100:.1f}%) vs Base: {base_eval['correct_total']}/200 ({base_eval['accuracy']*100:.1f}%)", fontsize=13, fontweight="bold")
    ax1.set_xticks(x)
    ax1.set_xticklabels(bench_names, rotation=35, ha="right", fontsize=9, fontweight="bold")
    ax1.set_ylim(0, 115)
    ax1.grid(axis="y", linestyle="--", alpha=0.4)
    ax1.legend(loc="upper left", fontsize=11)

    # Hardware & PPL Subplot
    metrics = ["Wikipedia PPL\n(Lower=Better)", "Peak VRAM (GB)\n(Lower=Better)", "Throughput (tok/s)\n(Higher=Better)"]
    base_m = [base_ppl, base_peak_vram / 1024, base_eval["throughput_tokens_per_sec"]]
    hadl_m = [hadl_ppl, hadl_peak_vram / 1024, hadl_eval["throughput_tokens_per_sec"]]

    xm = np.arange(len(metrics))
    ax2.bar(xm - width/2, base_m, width, label="Base Qwen-2B", color="#78909C", alpha=0.9)
    ax2.bar(xm + width/2, hadl_m, width, label="HADL v4.5 Dual-Cup", color="#1565C0", alpha=0.95)

    for i, (bm, hm) in enumerate(zip(base_m, hadl_m)):
        ax2.text(i - width/2, bm * 1.03, f"{bm:.2f}", ha="center", va="bottom", fontsize=9, fontweight="bold")
        ax2.text(i + width/2, hm * 1.03, f"{hm:.2f}", ha="center", va="bottom", fontsize=9, fontweight="bold")

    ax2.set_xticks(xm)
    ax2.set_xticklabels(metrics, fontsize=10, fontweight="bold")
    ax2.set_title("System Hardware & Stability Metrics", fontsize=11, fontweight="bold")
    ax2.grid(axis="y", linestyle="--", alpha=0.4)
    ax2.legend(loc="upper right", fontsize=10)

    plt.tight_layout()
    GRAPH_OUT.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(GRAPH_OUT, dpi=200)
    plt.close()

    if ARTIFACT_DIR.exists():
        shutil.copy(GRAPH_OUT, ARTIFACT_DIR / "hadl_v45_dualcup_200q_audit.png")
    print(f"[Graph] Saved to {GRAPH_OUT} and artifact directory.")


if __name__ == "__main__":
    main()
